version: '3'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      - VIRTUAL_HOST=wordpress.esgi.com
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=exampleuser
      - WORDPRESS_DB_PASSWORD=examplepass
      - WORDPRESS_DB_NAME=exampledb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=exampledb
      - MYSQL_USER=exampleuser
      - MYSQL_PASSWORD=examplepass
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db:/var/lib/mysql

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

# self signed
  omgwtfssl:
    image: paulczar/omgwtfssl
    restart: "no"
    volumes:
      - certs:/certs
    environment:
      - SSL_SUBJECT=wordpress.esgi.com
      - CA_SUBJECT=my@example.com
      - SSL_KEY=/certs/wordpress.esgi.com.key
      - SSL_CSR=/certs/wordpress.esgi.com.csr
      - SSL_CERT=/certs/wordpress.esgi.com.crt
    networks:
      - proxy-tier

volumes:
  wordpress:
  db:
  certs:
  acme:
  vhost.d:
